#!/bin/bash

echo '********************'
echo 'now run the bundle command'
echo '********************'

chdir /var/www/voltrak
bundle install

echo '********************'
echo 'Finally move the startup script'
echo '********************'

curl -o /etc/init/voltrak.conf https://raw.github.com/lyondhill/voltrak/master/etc/init/voltrak.conf

service voltrak start

echo '********************'
echo '--------------------'
echo 'FINNISHED!'
echo '--------------------'
echo '********************'





