#!/bin/bash

echo '********************'
echo 'now run the bundle command'
echo '********************'

chdir /var/www/voltrak
bundle install

RAILS_ENV=production bundle exec rake assets:precompile
RAILS_ENV=production bundle exec rake db:seed
echo '********************'
echo 'Finally move the startup script'
echo '********************'

cp -f etc/init/* /etc/init

service voltrak start
service voltrak-worker start
service voltrak-clock start

echo '********************'
echo '--------------------'
echo 'FINNISHED!'
echo '--------------------'
echo '********************'
