#!/bin/bash

echo '********************'
echo 'pulling git_repo'
echo '********************'

mkdir -p /var/www

chdir /var/www

git clone git://github.com/lyondhill/voltrak.git

chdir /var/www/voltrak

echo '********************'
echo 'now run the bundle command'
echo '********************'

chdir /var/www/voltrak
bundle install

echo '********************'
echo 'Finally move the startup script'
echo '********************'

cp -f etc/init/* /etc/init

service voltrak start
service voltrak-worker start
service voltrak-clock start

echo '********************'
echo '--------------------'
echo 'FINNISHED!'
echo '--------------------'
echo '********************'
